name: data-access-gateway
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.8.2
  - pip:
    - flask==1.1.1
    - marshmallow==3.5.1
    - psycopg2-binary==2.8.4
    - requests==2.23.0
    - rdflib==5.0.0
    - flask-cors==3.0.8
