name: model-sharing-platform
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.8.2
  - pip:
    - apispec==3.3.0
    - apispec-webframeworks==0.5.2
    - bcrypt==3.1.7
    - faker==4.0.2
    - flasgger==0.9.4
    - flask==1.1.2
    - flask-cors==3.0.8
    - flask-jwt-extended==3.25.0
    - flask-sqlalchemy==2.4.3
    - jsonschema==3.2.0
    - marshmallow==3.5.2
    - psycopg2-binary==2.8.4
    - pytest==5.4.1
    - rdflib==4.2.2
    - requests==2.23.0
    - sparqlwrapper==1.8.5
    - sqlalchemy==1.3.17
    - jellyfish==0.8.2
    - ../unit-translation-component
